# Generated by Django 3.2.1 on 2023-03-13 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='points',
            field=models.IntegerField(default=0),
        ),
    ]
