# Generated by Django 3.2.1 on 2023-03-23 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0003_alter_game_publicid'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='questionnaire',
            options={'ordering': ['-id']},
        ),
        migrations.AlterField(
            model_name='game',
            name='countdownTime',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='questionNo',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='answerTime',
            field=models.IntegerField(default=20),
        ),
    ]
