# Generated by Django 3.2.1 on 2023-03-24 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0006_alter_game_questionno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='questionNo',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
