# Generated by Django 3.2.1 on 2023-03-25 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0005_auto_20230324_1036'),
        ('models', '0007_alter_game_questionno'),
    ]

    operations = [
    ]
