# Generated by Django 3.2.1 on 2023-03-25 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0008_merge_20230325_1511'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='countdownTime',
            field=models.IntegerField(default=5, null=True),
        ),
    ]
