# Generated by Django 3.2.1 on 2023-04-07 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0011_auto_20230402_1857'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='participant',
            options={'ordering': ['-points', 'alias']},
        ),
    ]
