# Generated by Django 3.2.1 on 2023-04-07 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0012_alter_participant_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='alias',
            field=models.CharField(max_length=50),
        ),
    ]
