# Generated by Django 3.2.1 on 2023-04-14 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0013_alter_participant_alias'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='answer',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ['id']},
        ),
        migrations.AlterUniqueTogether(
            name='guess',
            unique_together={('participant', 'question')},
        ),
    ]
