# Generated by Django 3.2.1 on 2023-04-25 20:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0014_auto_20230414_1548'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='guess',
            unique_together={('participant', 'question', 'game')},
        ),
    ]
